name: Download Artifact
on:
  workflow_dispatch


permissions:
  contents: read

jobs:
  upload_artifact:
    uses: ./.github/workflows/upload_artifact.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: upload_artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: test
      
      # - uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const runid = await github.rest.actions.getWorkflow({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         workflow_id: 'upload_artifact.yml'
      #       })
      #       console.log(runid)
        
      
