name: Generate JSON file

on:
  workflow_dispatch:

env:
  file_path: .github/variables/testing.json

permissions:
  contents: read

jobs:
  generate-json:
    name: Generate JSON file
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON file
        id: jsonfile
        shell: pwsh
        run: |
          $jsonfile = Get-Content -Raw -Path $env:file_path | ConvertFrom-Json
          Write-Host '$jsonfile'