name: Generate JSON file

on:
  workflow_dispatch:

env:
  file_path: .github/variables/testing.json

permissions:
  contents: read

jobs:
  generate-json:
    name: Generate JSON file
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON file
        id: jsonfile
        shell: pwsh
        run: |
          $jsonfile = Get-Content -Raw -Path $env:file_path | ConvertFrom-Json
          $data = @{
            url = $jsonfile.common.url
            prefix  = $jsonfile.uk.nonprod.prefix
            resource_group  = $jsonfile.uk.nonprod.resource_group
            account_name  = $jsonfile.uk.nonprod.account_name
          }

          $jsonData = $data | ConvertTo-Json -Depth 5
          Set-Content -Path "${{github.workspace}}/product_info.json" -Value $jsonData

      - name: Upload Json
        uses: actions/upload-artifact@v4
        with:
          name: product_info.json
          path: ${{github.workflow}}/product_info.json