name: Main workflow
on: 
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: choice
        options:
          - us
          - uk
      environment:
        required: true
        type: choice
        options:
          - nonprod
          - stage
          - prod


jobs:
  init_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Export variables
        id: export_vars
        run: |
          yq '.${{ inputs.region }}.${{ inputs.environment }}.resource-group' ${{github.workspace}}/vars/common.yaml
    outputs:
      resource_group: ${{ steps.export_vars.outputs.resource_group }}
      sql_user: ${{ steps.export_vars.outputs.sql_user }}
  build:
    uses: ./.github/workflows/plan.yml
    needs: init_config
    with:
      resource_group: ${{needs.init_config.outputs.resource_group}}
      sql_user: ${{needs.init_config.outputs.sql_user}}
      env_name: testing   
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}