name: Main workflow
on: 
  workflow_dispatch:

jobs:
  one:
    uses: ./.github/workflows/plan.yml
    with:
      username: mona
      env_name: testing
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  second:
    uses: ./.github/workflows/plan.yml
    with:
      username: joan
      env_name: testing
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}