name: Matrix
on:
  workflow_dispatch:
    inputs:
      var_list:
        description: 'aaa'
        required: true
        type: string

jobs:
  getvariables:
    runs-on: windows-latest
    steps:
      - name: Get Vars
        id: vars
        shell: pwsh
        run: |
          $items = "${{ inputs.var_list }}" -split ','
          $matrix = @{ version = @($items) } | ConvertTo-Json -Compress
          echo "NAMES=$matrix" >> $env:GITHUB_OUTPUT
    outputs:
      NAMES: ${{ steps.vars.outputs.NAMES }}
    
  matrix_testing:
    runs-on: windows-latest
    needs: getvariables
    strategy:
      matrix: ${{ fromJson(needs.getvariables.outputs.NAMES) }}
    steps:
      - name: Remote Actions
        shell: pwsh
        run: .\scripts\remote-ops.ps1 -ComputerName "${{ matrix.servers }}" -Username $env:REMOTE_USER -Password $env:REMOTE_PASS