name: Plan Testing
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      env_name:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}
          enable-AzPSSession: true
        
      - name: Load Variables
        shell: pwsh
        run: |
          $ResourceGroup='Recursos'
          echo "::add-mask::$ResourceGroup"
          echo "RG_NAME=$ResourceGroup" >> "$Env:GITHUB_ENV"

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzResourceGroup -Name $Env:RG_NAME