name: Test-Plan
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      uk_np:
        required: true
        type: boolean
        default: false
      uk_pd:
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Load Variables
        shell: pwsh
        run: |
          echo ${{ inputs.uk_np }}
          echo ${{ inputs.uk_pd }}
          echo ${{ inputs.logLevel }}
          echo "RG_NAME=Recursos" >> "$Env:GITHUB_ENV"

      - name: Check Azure Context
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzResourceGroup -Name $Env:RG_NAME