name: Test-Plan
on:
  push

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Load Variables
        run: echo "env_vars=${{ vars.TEST }}" >> $GITHUB_ENV

      - name: Check Azure Context
        run: |
          echo Generic-Command --p ${{ env.env_vars }}