name: Upload Artifact
on:
  workflow_call


permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: README.md
      
      - name: Display Run ID
        run: echo "${{ github.run_id }}"
